In [1]:
import numpy as np

1) Создать массив из 100 целочисленных элементов от 70 до 170

In [2]:
a = np.arange(70, 171, dtype=np.int16)
a

array([ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
       161, 162, 163, 164, 165, 166, 167, 168, 169, 170], dtype=int16)

2) Создать массив чисел от 0 до 10 типа float

In [3]:
a = np.arange(10, dtype=np.float32)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

3) Создать массив чисел от ⅕ до 1/15 типа float

In [4]:
a = np.arange(5, 16, dtype=np.uint8)
a = 1. / a
a

array([0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

4)  Сформировать массив из ста пятёрок (все элементы - числа "5", целые, без знака, 1 байт)

In [5]:
a = np.full(100, 5, dtype=np.uint8)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=uint8)

5) Сформировать матрицу 5 x 5 из случайных чисел от 0 до 10 (float64), Гауссово распределение

In [6]:
# вариант 1
a1 = np.random.randn(5,5)
a1[a1<0] = 0
a1[a1>10] = 10
a1

array([[0.        , 0.        , 0.29147838, 0.        , 0.64884886],
       [0.88470054, 0.5312662 , 0.        , 1.53075378, 0.        ],
       [0.64790927, 0.97273206, 0.        , 0.58746612, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.04379339],
       [0.07156728, 0.08488192, 0.11156385, 0.        , 0.        ]])

In [7]:
# вариант 2
a2 = np.random.randn(5,5) + 5
a2[a2<0] = 0
a2[a2>10] = 10
a2

array([[4.47069837, 5.04398046, 4.0390702 , 4.67555313, 4.69915692],
       [6.69672185, 5.53557922, 4.80557019, 4.21750735, 5.38253243],
       [5.35531006, 5.40336604, 6.03633061, 7.55945922, 3.5859588 ],
       [4.92525423, 4.95228632, 5.45757487, 5.66987963, 3.46805864],
       [4.2133483 , 4.80730753, 5.85608888, 3.68048   , 4.84362494]])

6) Создать массив чётных чисел от 2 до 100. Элементам от 40 до 54 включительно поменять знак на отрицательный.

In [8]:
a = np.arange(2, 100, 2, dtype=np.int8)
a[(a >= 40) & (a <= 54)] *= -1
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38, -40, -42, -44, -46, -48, -50, -52,
       -54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98], dtype=int8)

7) Создать матрицу 10x10 с нулями внутри и единицами на границах

In [9]:
a = np.zeros((10,10), dtype=np.uint8)
a[:,(0, -1)] = 1
a[(0, -1),:] = 1
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

8) Сформировать массив из 100 случайных чисел, положительных и отрицательных. Создать второй массив такого же размера, где на месте неотрицательных чисел (из первого массива) будут стоять единицы, а отрицательных - минус единицы. Сделать то же самое, но булевый массив True/False.

In [10]:
a = np.random.randn(100)
b = np.ones_like(a, dtype=np.int8)
b[a < 0] = -1
b

array([ 1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,  1,  1,
       -1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1,
       -1, -1, -1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1, -1, -1,
        1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,
        1, -1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1,  1, -1,  1,  1,
       -1, -1, -1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1,  1],
      dtype=int8)

In [11]:
c = a > 0
c

array([ True,  True, False, False, False, False, False, False, False,
        True, False,  True,  True, False, False,  True,  True, False,
       False,  True, False, False, False, False,  True,  True,  True,
       False,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False,  True, False,  True, False, False, False,
       False, False,  True,  True, False,  True,  True, False, False,
        True, False,  True,  True, False, False, False, False,  True,
       False, False,  True, False,  True, False, False,  True, False,
        True])

9) Составить матрицы для решения этой системы уравнений и решить её.

https://www.webmath.ru/poleznoe/images/slau/formules_973.png


In [12]:
A = np.array([[2,1,1],[1,-1,0],[3,-1,2]])
B = np.array([2,-2,2])
res = np.linalg.solve(A, B)
res

array([-1.,  1.,  3.])